apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-0889e2a4d6d693e13, subnet-0689de445b67b123e
    alb.ingress.kubernetes.io/target-type: instance
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /stores
          pathType: Prefix
          backend:
            service:
              name: service-store
              port:
                number: 80
        - path: /categories
          pathType: Prefix
          backend:
            service:
              name: service-item
              port:
                number: 80
        - path: /orders
          pathType: Prefix
          backend:
            service:
              name: service-order
              port:
                number: 80
        - path: /sales
          pathType: Prefix
          backend:
            service:
              name: service-sale
              port:
                number: 80
