apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-sale
spec:
  selector:
    matchLabels:
      app: sale
  replicas: 1
  template:
    metadata:
      labels:
        app: sale
    spec:
      containers:
      - name: sale-app
        image: 370080849531.dkr.ecr.ap-northeast-2.amazonaws.com/sale-service
        ports:
        - containerPort: 5000
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-order
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sale-order
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: service-sale
spec:
  selector:
    app: sale
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: NodePort
